x-env: &env
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: ${POSTGRES_PORT}
  POSTGRES_USER_FILE: /run/secrets/postgres_user
  POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password

x-secrets: &secrets
  - postgres_user
  - postgres_password

secrets:
  postgres_user:
    environment: POSTGRES_USER
  postgres_password:
    environment: POSTGRES_PASSWORD

services:
  task:
    build:
      context: .
      dockerfile: ./services/task/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment: *env
    secrets: *secrets
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./services/task/migrations/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - SWAGGER_JSON=/swagger/swagger.yaml
    volumes:
      - ./services/task/docs/api/v1:/swagger
